# Generated by Django 6.0.5 on 2026-05-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('position', models.CharField(choices=[('hero_carousel', 'Hero Carousel'), ('hero_side_top', 'Hero Side Top'), ('hero_side_bottom', 'Hero Side Bottom'), ('mid_banner', 'Mid Banner'), ('lower_mid_banner', 'Lower Mid Banner')], max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
