# Generated by Django 6.0.5 on 2026-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('hero_carousel', 'Hero Carousel'), ('hero_side_top', 'Hero Side Top'), ('hero_side_bottom', 'Hero Side Bottom'), ('category_banner', 'After Category (50-50)'), ('brand_banner', 'After Brands (100% Width)'), ('pre_review_banner', 'Before Reviews (60-40)')], max_length=50),
        ),
    ]
