# Generated by Django 6.0.5 on 2026-05-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_banner_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='কুপন কোড (যেমন: EID50, NEWYEAR200)', max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='কত টাকা ডিসকাউন্ট হবে', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='মিনিমাম কত টাকার অর্ডার করতে হবে', max_digits=10)),
                ('valid_from', models.DateTimeField(help_text='কবে থেকে কুপনটি কাজ করবে')),
                ('valid_to', models.DateTimeField(help_text='কবে কুপনটির মেয়াদ শেষ হবে')),
                ('is_active', models.BooleanField(default=True, help_text='কুপনটি অ্যাক্টিভ আছে কি না')),
            ],
        ),
    ]
